drop table if exists bookings;
drop table if exists comments;
drop table if exists items;
drop table if exists users;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(2000)                           NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT ref_user_id FOREIGN KEY (user_id) REFERENCES users (ID)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         bigint generated by default as identity not null,
    start_data TIMESTAMP                               NOT NULL,
    end_data   TIMESTAMP                               NOT NULL,
    status     varchar(255) check (status in ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED')),
    user_id    bigint                                  NOT NULL,
    item_id    bigint                                  NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT ref_user_id2 FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ref_item_id FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR NOT NULL ,
    created TIMESTAMP NOT NULL ,
    item_id BIGINT NOT NULL ,
    user_id BIGINT NOT NULL ,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT ref_comments_item_id FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT ref_comments_user_id FOREIGN KEY (item_id) REFERENCES users (id)
);